version: '3.8'

services:
    nginx-proxy:
      image: jwilder/nginx-proxy
      ports:
        - "80:80"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
  
    app:
      environment:
        - VIRTUAL_HOST=api.buddyaplicativo.com.br