/* eslint-disable global-require */
module.exports = {
  AgendaController: require('../app/controllers/AgendaController'),
  AgendamentoController: require('../app/controllers/AgendamentoController'),
  CategoriaController: require('../app/controllers/CategoriaController'),
  FileController: require('../app/controllers/FileController'),
  ForgetPasswordController: require('../app/controllers/ForgetPasswordController'),
  ForgetPasswordProviderController: require('../app/controllers/ForgetPasswordProviderController'),
  PetController: require('../app/controllers/PetController'),
  ProviderController: require('../app/controllers/ProviderController'),
  PostController: require('../app/controllers/PostController'),
  SessionController: require('../app/controllers/SessionController'),
  SessionProviderController: require('../app/controllers/SessionProviderController'),
  UserController: require('../app/controllers/UserController'),
  VacinaController: require('../app/controllers/VacinaController'),
  NotificationController: require('../app/controllers/NotificationController'),
  CreditCardController: require('../app/controllers/CreditCardController'),
  EnderecoController: require('../app/controllers/EnderecoController'),
  TypeOfProviderController: require('../app/controllers/TypeOfProviderController'),
};
